name: CycloneDX SBOM with cyclonedx-npm

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CycloneDX NPM tool
      run: npm install -g @cyclonedx/cyclonedx-npm

    - name: Install dependencies
      run: npm install


    - name: Generate SBOM
      run: cyclonedx-npm --output-file sbom.json --output-format json


    - name: Commit SBOM to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add sbom.json
        git commit -m "Add generated SBOM for review" || echo "No changes to commit"
        git push
